MSTR-155 : 유저 조회 페이지 생성
SW13-Monstera/admin-frontend pull request #6
Opened 2022-08-11 14:55 UTC by Kim-Hyunjo

- 전체 유저 조회 가능
- id, email, username, role 필드

2022-08-11 16:06 UTC, kshired requested changes
1. UserTable 컴포넌트가 이상한 것 같습니다. ProblemTable과 로직 및 요청하는 API까지 똑같습니다.

2. 1에 따라, 각 Table의 구성요소와 테이블을 구성하는 방식이 유사하다면 공통적으로 사용하는 Table 컴포넌트를 만들어 DRY 원칙을 지켜서 개발하면 좋을 것 같습니다.

3. Enhanced 라는 이름을 가진 컴포넌트들의 명명 이유가 무엇일까요? 의도가 드러나지 않는 이름인 것 같아요.

2022-08-11 16:06 UTC, kshired commented on src/pages/user/UserPage.tsx
> +  }, []);
users 라는 State가 실질적으로 사용되지 않아, 의미없는 두번의 호출을 일으킬 것 같은데 삭제해도 좋을 것 같습니다.

2022-08-11 16:06 UTC, kshired commented on src/Router.tsx
> +        <Route path={URL.USER} element={<UserPage />} />
각 라우팅 path들이 나열식으로 되어있어, 한 번에 파악하기 쉽지 않습니다.
의미를 가진 단위별로 구분하여, 중첩 라우팅을 해보는게 어떨까요?

> 참고 : https://basemenks.tistory.com/248

2022-08-11 16:06 UTC, kshired commented on src/components/Menu/MenuBarItems.tsx
> +      </Collapse>
```js
<>
      <MenuBarTitle text='사용자 관리' open={userMenuOpen} handleClick={handleUserMenu} />
      <Collapse in={userMenuOpen} timeout='auto' unmountOnExit>
        <List component='div' disablePadding>
          <MenuBarListElement text='전체 사용자' icon={<PeopleAltIcon />} url={URL.USER} />
        </List>
      </Collapse>
</>
```

위와 같은 구조가 반복됩니다. 
컴포넌트 이름도 `MenuBarItems` 라면, 각 단위를 새로운 컴포넌트 ( ex) `MenuBarItem` ) 로 묶어서 분리해봐도 좋을 것 같습니다.

2022-08-11 16:06 UTC, kshired commented on src/components/Table/EnhancedTableHead.tsx
> +              'aria-label': 'select all desserts',
```suggestion
              'aria-label': 'select all items',
```

2022-08-11 16:06 UTC, kshired commented on src/components/Table/UserTable.tsx
> +                <TableRow
map 에 들어가는 return문의 크기가 너무 크고, Table이라는 컴포넌트들에서 반복적으로 사용되는 컴포넌트라면 새로운 함수형 컴포넌트로 분리하면 좋을 것 같아요.

2022-08-16 08:07 UTC, Kim-Hyunjo commented on src/pages/user/UserPage.tsx
> +  }, []);
확인했습니다! 감사합니다!

2022-08-16 08:08 UTC, Kim-Hyunjo commented on src/Router.tsx
> +        <Route path={URL.USER} element={<UserPage />} />
이거 넘 하고싶은데 이렇게 하면 바깥쪽에 있는 route가 안쪽에 있는 route를 포함하도록 렌더링되어요. 어케하면 UI에는 영향을 안주면서 멋진 중첩라우팅을 할 수 있나요?

2022-08-16 08:08 UTC, Kim-Hyunjo commented on src/components/Menu/MenuBarItems.tsx
> +      </Collapse>
확인하여 반영했습니다 감사합니다!!

2022-08-16 08:08 UTC, Kim-Hyunjo commented on src/components/Table/EnhancedTableHead.tsx
> +              'aria-label': 'select all desserts',
대박적

2022-08-16 08:08 UTC, Kim-Hyunjo commented on src/components/Table/UserTable.tsx
> +                <TableRow
Table 리팩토링 시러 그렇지만 했습니다

2022-08-16 08:39 UTC, closed without merging